### ISSUE TITLE
ubuntu 16.04 无法编译通过。

### ISSUE THREAD

**Issue by noparkinghere** [rekols/dict-examples#1]
PKGCONFIG += dtkwidget dtkbase dtkutil

这几个是不是 deepin 提供的？

**Comment by rekols** [comment]
用了深度的DTK，ubuntu的话你可以到http://packages.deepin.com/deepin/pool/main/d/deepin-tool-kit/
下载这几个包：
libdtkbase libdtkwidget libdtkutil
libdtkbase-dev libdtkwidget-dev libdtkutil-dev

**Comment by noparkinghere** [comment]
@rekols 好的，谢谢啦！
